CREATE DATABASE EventPlus;
GO

USE EventPlus;
GO

CREATE TABLE TipoUsuario(
	Id_TipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo VARCHAR(100) NOT NULL
);
GO


CREATE TABLE TipoEvento(
		Id_TipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
		Titulo VARCHAR(100) NOT NULL
);
GO


CREATE TABLE Usuario(
	Id_Usuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL,
	Senha VARCHAR(60) NOT NULL,

	Id_TipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(Id_TipoUsuario)
);
GO


CREATE TABLE Instituicao(
	Id_Instituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	NomeFantasia VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) UNIQUE NOT NULL,
	Endereco VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Evento
(
	Id_Evento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	DataEvento DATETIME NOT NULL,
	Descricao TEXT NOT NULL,

	Id_TipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento(Id_TipoEvento),
	Id_Insituicao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao(Id_Instituicao)
);
GO


CREATE TABLE Presenca(
	Id_Presenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Situacao BIT NOT NULL,

	Id_Usuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(Id_Usuario),
	Id_Evento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(Id_Evento)
);
GO


CREATE TABLE ComentarioEvento(
	Id_ComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Descricao VARCHAR(200)NOT NULL,
	Exibe BIT NOT NULL,
	DataComentarioEvento DATETIME NOT NULL,

	Id_Usuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(Id_Usuario),
	Id_Eveto UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(Id_Evento)
);
GO