CREATE DATABASE GerenciamentoDePets;

USE GerenciamentoDePets;

CREATE TABLE Pet(
    IdPet UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Nome VARCHAR(100) NOT NULL,
    Peso FLOAT NOT NULL,
    Idade VARCHAR(2) NOT NULL,
    Imagem VARCHAR(100),
    IdResponsavel UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Responsavel(IdResponsavel),
    IdTipoPet UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoPet(IdTipoPet)
);

CREATE TABLE Responsavel(
    IdResponsavel UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Nome VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    Telefone NVARCHAR(255) NOT NULL
);

CREATE TABLE TipoPet(
    IdTipoPet UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Especie VARCHAR(100) NOT NULL
);

SELECT * FROM Pet;
SELECT * FROM Responsavel;
SELECT * FROM TipoPet;